version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: database
    volumes:
      - ./docker/:/etc/mysql/conf.d
      - ./docker/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=explorer
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12dlql*41
  app:
    build: .
    tty: true
    image: explorer-cli:latest
    container_name: explorer-cli
    volumes:
      - ./src:/go/src
    external_links:
      - database
